---
- name: Install Playwright
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install Playwright
      ansible.builtin.command:
        cmd: npm install --save-dev playwright@1.57.0
        chdir: "{{ playbook_dir }}/.."